import { Comfortaa, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Footer from "../components/Footer/footer";
import NavBar from "../components/Navbar";
import Head from "./Head";
import Providers from "../Providers/providers";

import Maintainance from "../components/maintainance/Maintainance";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const comfortaa = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ["latin"],
});

export const metadata = {
  // title: "Kappes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head />
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${comfortaa.variable} antialiased`}
      >
        <Providers>
          <NavBar />
          <div className="">
            <Maintainance />
            {/* {children} */}
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
